require:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['^(\s*#)']

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'spec/**/*'
    - '**/vendor/**/*'
  NewCops: enable

Naming/RescuedExceptionsVariableName:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10
