version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -b 0.0.0.0
    container_name: quiz-api
    ports:
      - 3000:3000
    volumes:
      - .:/app/quiz-api
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - quiz_api_data:/var/lib/postgresql/data
volumes:
  quiz_api_data:
