default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRESQL_USER'] || 'postgres' %>
  database: <%= ENV['POSTGRESQL_DATABASE'] || 'quiz_api_development' %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_HOST'] || 'localhost' %>
  pool: <%= ENV['POSTGRESQL_POOL'] || 5 %>
  port: <%= ENV['POSTGRESQL_PORT'] || 5432 %>

development:
  <<: *default

test:
  <<: *default
  database: 'quiz_api_test'

production:
  <<: *default
